return { 
	Damage = 5,
	Health = 5,
	Tier = 2,
	XP = 0,
	MaxXP = 2,
	Level = 1,
	MaxLevel = 3,
	Cost = 5,
	RoundStartEffect = nil,
	DamageReceivedEffect = nil,
	OnDeathEffect = "UpgradeBehind",
	OnKillEffect = nil,
	RoundEndEffect = nil,
	BuyEffect = nil,
	SellEffect = nil,
	LevelUpEffect = nil,
	FriendSummonedEffect = nil,
	EnemySummonedEffect = nil,
	ImageID = "rbxassetid://10171565486",
}