return { 
	Damage = 2,
	Health = 2,
	Tier = 1,
	XP = 0,
	MaxXP = 2,
	Level = 1,
	MaxLevel = 3,
	Cost = 3,
	RoundStartEffect = "RandomAttack",
	DamageReceivedEffect = nil,
	OnDeathEffect = nil,
	OnKillEffect = nil,
	RoundEndEffect = nil,
	BuyEffect = nil,
	SellEffect = nil,
	LevelUpEffect = nil,
	FriendSummonedEffect = nil,
	EnemySummonedEffect = nil,
	ImageID = "rbxassetid://10147977564",
}